sonar.projectKey=homeassistant_custom_refrigerator_card
sonar.projectName=Home Assistant Custom Refrigerator Card
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/unit/**/*.test.mjs
sonar.exclusions=dist/**,coverage/**,reports/**,.stryker-tmp/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
